### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by dgrmunch** [donmccurdy/aframe-proxy-controls#10]
Do you know if this component works currently on iOS?
It's being a couple of years so that may be possible, right?

**Comment by donmccurdy** [comment]
I did eventually add a WebSocket fallback, which works in iOS. 

Recently iOS added support for WebRTC, so in theory it doesn't even need that fallback, but I haven't tested that yet.

**Comment by dgrmunch** [comment]
Thanks! I will check it up ;)

[image: SciArt Lab] <http://www.sciartlab.com/>

Diego González, PhD | Research & Development

xmunch@xmunch.com

*Personal website*: http://www.xmunch.com

*SciArt Lab*:  http://www.sciartlab.com




This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
If you want to encrypt our communications we can use cryptographic tools.
You can find my PGP public key here: http://xmunch.com/pgp.
